Feature/pn 1148
pagopa/pn-mandate pull request #20
Opened 2022-07-08 06:38 UTC by cFiorilloMediatica

2022-07-08 11:24 UTC, fabriziolana requested changes
Manca la classe di test che ci siamo detti

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
> +                    })).then().onErrorResume(throwable -> {
Qui l'onErrorResume non è al posto corretto, probabilmente bisogna mettere quella logca all'interno di un "exceptionally" tra "transactWriteItems e "thenApply a riga 239

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
> +        log.info(logMessage);
non serve .info

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
>                          return mandateTable.putItem(putRequest).thenApply(x -> {
anche qui manca "exceptionally" tra putitem e thenapply riga 398 con il tracciamento del fallimento

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
> +    private CompletableFuture<MandateEntity> saveHistoryAndDeleteFromMain(MandateEntity mandate, StatusEnum newstatus, PnAuditLogEvent logEvent)
questo metodo è usato per salvare "più eventi" molto simili tra loro.
puoi aggiungere direttamente qui dentro i vari logEvent in base al "newStatus" richiesto mettendo a riga 523 diciamo la creazione del log (quindi non serve farselo passare nel costruttore, usa il builder).
e poi aggiungendo a riga 533 tra transactWriteItems e thenapply, un "exceptionally" con dentro il catch - log -rethrow dell'errore

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
> +        String logMessage = String.format("expireMandate for delegate uid=%s{} mandateid=%s", delegatorInternaluserid, mandateId);
Vedi commento sotto di aggregazione eventi.

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
> +        String logMessage = String.format("revokeMandate for delegate uid=%s mandateid=%s", delegatorInternaluserid, mandateId);
Vedi commento sotto di aggregazione eventi.

2022-07-08 11:24 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/mandate/middleware/db/MandateDao.java
>                          // aggiorno lo stato, solo se era in pending o active, ignoro eventuali altri stati (che NON dovrebbero essere presenti)
Vedi commento sotto di aggregazione eventi.

2022-07-12 14:38 UTC, MTurraPpa approved these changes

2022-07-12 14:39 UTC, MTurraPpa requested changes
Scusa, lo iun va messo nei log come metodo

2022-07-13 12:55 UTC, merged